rust/projects/project-3/project.md: Remove --release reference
`cargo bench` does not support the `--release` flag. According to the
Cargo book [1]:

> Benchmarks are always built with the bench profile. Binary and lib
> targets are built separately as benchmarks with the bench profile.
> Library targets are built with the release profiles when linked to
> binaries and benchmarks. Dependencies use the release profile.

```bash
$ cargo --version
cargo 1.36.0 (c4fcfb725 2019-05-15)

$ cargo bench --release
error: Found argument '--release' which wasn't expected, or isn't valid
in this context

USAGE:
    cargo bench [OPTIONS] [BENCHNAME] [-- <args>...]

For more information try --help
```

[1]
https://doc.rust-lang.org/cargo/commands/cargo-bench.html#cargo-bench